spring:
  application:
    name: heythere-video-streaming-server
  datasource:

  h2:
    console:
      path: /h2
      enabled: true
  config:
    location:
      - classpath:aws.yml
      - classpath:database.yml
  servlet:
    multipart:
      max-request-size: 1000MB
      max-file-size: 1000MB
  kafka:
    consumer:
      bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
      key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: heythere
    producer:
      bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        acks: all
        retries: 10
        retry.backoff.ms: 1000

server:
  port: 8082
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

cloud:
  aws:
    credentials:
      accessKey: AKIAJF2FHSSU7QJJMHXA
      secretKey: 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
    s3:
      bucket: heythere-file-store
    region:
      static: ap-northeast-2
    stack:
      auto: false


